core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cuenta/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('pago/', include('payment.urls')),
    path('', include('inmuebles.urls')),
    path('enlaces-de-interes/', include('enlaces.urls')),
    # path('herramientas/', include('herramientas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

herramientas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('enlaces-de-interes/', views.PrincipalView.as_view(), name='enlaces'),
    path('simulador-de-hipoteca/', views.SimuladorHipoteca.as_view(), name='simulador_hipoteca'),
]

herramientas/models.py
from django.db import models

# Create your models here.

inmuebles/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model
User = get_user_model()

from allauth.account.signals import email_confirmed

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

class Image(models.Model):
    image = models.ImageField(blank=True, null=True)
    
    def __unicode__(self):
        return str(self.image)

class Ubicacion(models.Model):
    departamento = models.CharField(max_length=300)
    provincia = models.CharField(max_length=300)
    codigo_p = models.IntegerField(null=True, blank=True)
    ciudad = models.CharField(max_length=300)
    
    def __str__(self):return f'{self.departamento}, {self.provincia}, {self.ciudad}'
    
class Pricing(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    stripe_price_id = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    currency = models.CharField(max_length=60)
    
    def __str__(self):
        return self.name
    
class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, related_name='subscriptions')
    created = models.DateTimeField(auto_now_add=True)
    stripe_subscription_id = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    
    class Meta:
        ordering = ['-created',] 
        
    def __str__(self):
        return self.user.email
    
    @property
    def is_active(self):
        return self.status == "active" or self.status == "trialing"
    
class Plan(models.Model):
    name = models.CharField(max_length=400) 
    slug = models.SlugField(unique=True)
    paypal_id = models.CharField(max_length=500, blank=True)
    paypal_plan_id = models.CharField(max_length=500, blank=True)
    currency = models.CharField(max_length=60, default="COP")
    price = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    
    def __str__(self): return self.name  
    
class Suscripcion(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name="suscripciones")
    id_suscripcion = models.CharField(max_length=560, blank=True)
    ba_token = models.CharField(max_length=560, blank=True)
    token = models.CharField(max_length=560, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.plan.name}{self.created}')
        super().save(*args, **kwargs)
    
    def __str__(self): return self.user.email
    
#modelo de los inmuebles
class Inmueble(models.Model):
    
    #choices
    class Estado(models.TextChoices):
        NUEVO = 'Obra nueva', 'Obra nueva'
        USADO = 'Usado', 'Usado'        
    
    PREGUNTAS_CERRADAS = [(True, 'Si'), (False, 'No')]
 
    TIPO_INMUEBLE = [
        ('Casa', 'Casa'),('Apartamento', 'Apartamento'),('Local', 'Local'),('Oficina', 'Oficina'),('Bodega', 'Bodega'),('Vivienda vacacional', 'Vivienda vacacional'),
    ]
    
    TIPO_OPERACION = [('Venta', 'Venta'),('Arriendo', 'Arriendo'),('Permuta', 'Permuta'),]
        
    Tipo_de_inmueble = models.CharField(choices=TIPO_INMUEBLE, max_length=100, default='Casa')
    operacion = models.CharField(choices=TIPO_OPERACION, max_length=100, default='Venta')
    # ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE)
    # codigo_postal = models.PositiveIntegerField()
    ubicacion = models.TextField()
    Lat = models.CharField(max_length=140)
    Lng = models.CharField(max_length=140)
    precio = models.BigIntegerField()
    estado = models.CharField(max_length=30, choices=Estado.choices, default=Estado.NUEVO)
    portada = models.ImageField(upload_to='media/inmuebles/portadas/%Y/%m/%d')
    video = models.FileField(upload_to='media/inmuebles/videos/%Y/%m/%d', null=True, blank=True)
    image = models.ManyToManyField(Image, blank=True, related_name='inmueble')
    
    area = models.PositiveIntegerField()
    habitaciones = models.PositiveIntegerField()
    banos = models.CharField(max_length=6)
    valor_administracion = models.CharField(max_length=200, blank=True, null=True)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE)
    estrato = models.PositiveIntegerField(blank=True, null=True)
    antiguedad = models.PositiveIntegerField(default=0, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    parqueadero = models.BooleanField(choices=PREGUNTAS_CERRADAS, default=False)
    zonas_verdes = models.BooleanField(choices=PREGUNTAS_CERRADAS, default=False)
    zonas_ninos = models.BooleanField(choices=PREGUNTAS_CERRADAS, default=False)
    zona_comercial = models.BooleanField(choices=PREGUNTAS_CERRADAS, default=False)
    zona_residencial = models.BooleanField(choices=PREGUNTAS_CERRADAS, default=False)
    estudio = models.BooleanField(choices=PREGUNTAS_CERRADAS, default=False)
    published = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(unique=True, max_length=255, unique_for_date='published')
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    pricing_tiers = models.ManyToManyField(Pricing, blank=True)

    def __str__(self):
        return f'{self.Tipo_de_inmueble} de {self.vendedor.username} en {self.ubicacion}'
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.Tipo_de_inmueble}{self.pk} en {self.vendedor.id}{self.ubicacion}')
        super().save(*args, **kwargs)
    
    class Meta:
        ordering = ['-creado']
    
    

herramientas/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.http import HttpResponse, JsonResponse
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.views import View

class PrincipalView(TemplateView):
    template_name = 'herramientas/enlaces.html'
    
class SimuladorHipoteca(View):
    
    def get(self, request):
        years = ['2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30']
        context = {
            'years': years,
        }
        return render(request, 'herramientas/paginas/simuladorhipoteca.html', context)

templates/herramientas/paginas/simuladorhipoteca.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    - Simulador de hipoteca
{% endblock title %}

{% block content %}
    <div class="flex flex-col px-6 mx-auto h-screen pt:mt-0 pt-20">
        <div class="w-full p-6 space-y-8 sm:p-8 bg-white rounded-lg shadow">
            <h2 class="text-2xl font-bold text-gray-900 dark:text-white">
                Simulador de hipoteca
            </h2>

            <form class="mt-8 space-y-6" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
               <div class="flex">
                    <div class="flex-1 mr-4">
                        <label class="block text-lg mb-6 font-medium text-gray-90">Valor de la propiedad:</label>
                        <input id="valor_total" type="number" required class="block w-full p-2.5 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-transparent focus:border-none">
                    </div>
               </div>
            
               <div class="flex flex-wrap">
                    <div class="flex-1 mr-4">
                        <label class="block text-lg mb-6 font-medium text-gray-90">Valor del prestamo en %(no puede exceder el 80% ni ser inferior al 50%):</label>
                        <h2 class="block mb-6 font-medium text-xl text-gray-90 text-center" id="prestamo_porcentaje">
                            50%
                        </h2>
                        <input value="50" id="porcentaje_valor" type="range" min="50" max="80" required class="block w-full p-2.5 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-transparent focus:border-none">
                    </div>
               </div>
               <div class="flex flex-wrap">
                    <div class="flex-1 mr-4">
                        <h2 class="block text-lg mb-6 font-medium text-gray-90" id="prestamo_valor">
                            $0
                        </h2>
                    </div>
                </div>

                <div class="flex flex-wrap">
                    <div class="flex-1">
                        <label for="id_parqueadero" class="block text-sm font-medium text-gray-90">A qu&eacute; plazo necesitas el cr&eacute;dito:</label>
                        <br>
                        <select name="parqueadero" id="id_parqueadero" class="block w-full p-2 mb-6 text-sm outline-none focus:outline-none text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-transparent">
                            <option value="1">1 año</option>
                            {% for year in years %}
                                <option value="{{year}}">{{year}} Años</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="flex flex-wrap">
                    <div class="flex-1">
                        <label class="block text-lg mb-6 font-medium text-gray-90">Tasa de inter&eacute;s:</label>
                        <h2 class="block mb-6 font-medium text-xl text-gray-90 text-center" id="tasa_valor">
                            12%
                        </h2>
                        <input value="12" id="tasa_porcentaje" type="range" step="0.1" min="12" max="21" required class="block w-full p-2.5 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-transparent focus:border-none">
                    </div>
                </div>

                <input type="submit" class="w-full px-5 py-3 text-base font-medium text-center text-white bg-yellow-300 hover:bg-yellow-400 rounded-lg sm:w-auto" style="cursor:pointer;" value="Simular" id="btn-hipoteca">
            </form>
        </div>
        <br><br><br><br>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static 'javascript/herramientas/hipoteca/input.js' %}"></script>
{% endblock js %}